# Generated by Django 5.0.3 on 2024-03-28 09:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spaces", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notice",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 3, 28, 9, 23, 30, 594832, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
